apiVersion: v1
kind: Pod
metadata:
  name: kubepod2
spec:
  containers:
  - name: sise
    image: mcnac/lab2
    ports:
    - containerPort: 5000
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"